server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/courses/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/subscriptions/**

    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
